### PR TITLE
Basic HTML5 player implementation (#115).

### PR DESCRIPTION
**Pull request by sk4zuzu**
I haven't been able to do proper functional testing in PhantomJS due to https://github.com/ariya/phantomjs/issues/10839#issuecomment-14994323 ... :/

If you have better idea what should/could be tested please let me know. For now I think it should be safe to merge.

\\:D/

### CODE REVIEW

**Comment by sk4zuzu** [comment]
`The command "npm run selenium-download" failed and exited with 1 during .` 

pls...

**Comment by sk4zuzu** [comment]
:see_no_evil:

**Comment by lidel** [comment]
perfect

**Comment by sk4zuzu** [comment]
\\:D/

**Pull request merged**
